### ISSUE TITLE
Paragraph isn't indented after a list

### ISSUE THREAD

**Issue by slitjen** [stolksdorf/naturalcrit#101]
**Browser Type/Version**: [Google Chrome OS Version 51.0.2704.42 beta (64-bit)]

**Operating System**: [Google Chrome OS Version 51.0.2704.42 beta (64-bit)]

**Issue Description**: [Creating a bullet list seems to break body formatting, so that the paragraph after a bulleted list isn't indented.]

**Markdown code to reproduce**:

```
***Random Properties.*** The bow has the following randomly determined properties:

* 1 minor beneficial property
* 1 major beneficial property
* 2 minor detrimental properties

***Speed of Light.*** While attuned to the bow, your walking speed increases by 10 feet
```

**Related Images** :

![screenshot 2016-05-22 at 11 54 48 am](https://cloud.githubusercontent.com/assets/19520022/15455808/01ede550-2014-11e6-9571-c1269ec3ce17.png)

**Comment by stolksdorf** [comment]
Fixed in v2.1.0!
