### ISSUE TITLE
UI for printable page has advantage on Stealth checks

### ISSUE THREAD

**Issue by fuzzyspartan** [stolksdorf/naturalcrit#103]
**Browser Type/Version**: Google Chrome	50.0.2661.102

**Operating System**: Windows 10 of some kind

**Issue Description**: I can't find the UI to get to a printable version of the page.  Clicking the "print" button does nothing, and the 2 drop-down menu items that come from said print button are not as useful or relevant as actually being able to print.

Simply typing ctrl+p attempts to print the frame layout.

**Comment by fuzzyspartan** [comment]
So I couldn't find it because I was editing the launch page (which has a big "CREATE YOUR OWN" button), and wasn't aware that it was distinct.

Would recommend more visual distinction.

**Comment by stolksdorf** [comment]
More visual distinction like a giant orange button that says "Create your own" ? There's not much to fix, as soon as anyone hits the big button, or the "New Brew" button in the navbar, the flow becomes quite clear. Sorry for the confusion though.

**Comment by stolksdorf** [comment]
However, you get an inspiration die for having the best issue title so far!

**Comment by fuzzyspartan** [comment]
My take on it would be having the save / print buttons there, but greyed out, with a tooltip that says "This is just a demo, click Create Your Own to get started!" or something would have helped me a bit.  Thanks for the reply!

**Comment by stolksdorf** [comment]
The problem with that is that there's several items that would be greyed out and would clutter the nav bar (save, print, source, share). 

I"ve done some more thinking on this and I agree it needs to be addressed. I made a new issue #106 , For improving the clarity for the creation process in general. I think the best way to solve this is to just use the text in the welcome message, but write it to be less "pitch-y" and more "instruction-y"

**Comment by stolksdorf** [comment]
Better idea (from one of my friends). Show a save current button if someone modifies the home page
![screen shot 2016-05-24 at 4 07 07 pm](https://cloud.githubusercontent.com/assets/387742/15518563/7f09fa20-21cb-11e6-83fc-f16d51fb7b29.png)

**Comment by mimosacb** [comment]
I support this idea :P

**Comment by stolksdorf** [comment]
I may have went a bit overboard but this issue has been fixed in 3 ways

- The welcome page text has been updated a bit
- The save current button now pops out when you modify any text on the homepage, encouraging you to save
- Pressing `ctrl+p` on an edit or share page now will bring you to the print page automatically.

Whew! Shouldn't be much confusion anymore :)

Every is in v2.1.0
