### ISSUE TITLE
Make Ctrl+P / ⌘+P open print in new tab

### ISSUE THREAD

**Issue by mimosacb** [stolksdorf/naturalcrit#107]
**Browser Type/Version**: Google Chrome 50.0.2661.102

**Operating System**: OS X 10.10.5

**Issue Description**: I would like to have the same print behaviour between the UI "Print" button and the keyboard Ctrl+P / ⌘+P operation.

Currently the "Print" button opens my brew in a new tab with only the brew but the Ctrl+P / ⌘+P keyboard shortcut opens a dialog in the current tab and attempts to print the whole editor. I would like to have the keyboard behave the same way the button currently does.

**Comment by stolksdorf** [comment]
It's up [on staging](http://natural-crit-staging.herokuapp.com/homebrew/), but I have no idea if it works on mac. Can someone verify?

**Comment by mimosacb** [comment]
It works, but is using Ctrl instead of Cmd.

**Comment by stolksdorf** [comment]
Updated on staging

**Comment by stolksdorf** [comment]
Added in v2.1.0
