### ISSUE TITLE
Make the proficiency bonus in the generated class tables follow the right progression

### ISSUE THREAD

**Issue by stolksdorf** [stolksdorf/naturalcrit#108]
It's consistent across all classes, so no need getting it wrong, ya goof!

**Comment by stolksdorf** [comment]
Fixed in v2.0.4

**Comment by TheIrishBandit** [comment]
Default Ability Score Improvements should probably also be corrected.

**Comment by stolksdorf** [comment]
Fixed in v2.0.5
