### ISSUE TITLE
Content Frame not Resizing Vertically in Fullscreen

### ISSUE THREAD

**Issue by aczac** [stolksdorf/naturalcrit#109]
**Browser Type/Version**: Google Chrome 50

**Operating System**: Windows 10 Home

**Issue Description**: The content frame does not resize vertically in when fullscreen. Whenever I put my browser into fullscreen mode by pressing F11, there is a pretty large blue gap under the content frame.

**Related Images** :
![screenshot](https://cloud.githubusercontent.com/assets/19584144/15564400/f0ab24d2-22df-11e6-8a08-447f9f3cc302.jpg)

**Comment by stolksdorf** [comment]
Yeah I'm aware of this bug. It's actually pretty difficult to fix and has a low priority

For now, just wait until your brew is saved and refresh the page.
