### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by gCardinal** [stolksdorf/NaturalCrit#11]
I'm not sure if I should have posted this in the reddit post if so I'll just close this.

I noticed two typos in the documentation:

> Vertical spacing, column breaks, and mutliple Pages

Should be: multiple Pages

> New Pages are controlled by the author. It's impossible for the site to detect when the end of a page is reached, so indicate you'd like to start a new page with /page on it's own line .

Extra space before the last period and /page does not work, it's actually \page.

If I have time to create a pull request I will, but I'm not sure when that will be, so I thought I'd open an issue until then (if that moment ever comes).

**Comment by stolksdorf** [comment]
maxrothman got most of these in this [PR](https://github.com/stolksdorf/NaturalCrit/pull/8). I just commited the rest you pointed out and will be deploying shortly. Thanks!
