### ISSUE TITLE
Print to PDF issue

### ISSUE THREAD

**Issue by rob2ee** [stolksdorf/naturalcrit#110]
When I try to print to PDF it looks beutiful on the screen, but printing to any PDF (Adobe PDF, Microsoft Print to PDF, or PDF creator), none of those work.  The format is screwed up and it seems the graphics are blank.

Ideas as to what I'm doing wrong?

[Unknown Whom.zip](https://github.com/stolksdorf/naturalcrit/files/283644/Unknown.Whom.zip)

**Browser Type/Version**: [Google Ultron v90.01]

**Operating System**: [GLaDOS v34.5.8]

**Issue Description**: [The thing won't thing]

**Markdown code to reproduce**:

```
# thing
> thing 2
```

**Related Images** :

**Comment by stolksdorf** [comment]
You just need to tweak your printer settings before you print. On the homepage I have a few steps to walk through, so check that. The big issues here is that you don't have background images checked, and print-to-PDF is adding the locations and time as a header to each.

**Comment by rob2ee** [comment]
Hmm.  My three PDF options when I hit the print key don't HAVE settings to include images or not.  Even in the advanced settings that I can see.  I really want to figure this out.  I spent A LOT of time making my pages (and I'm not done), but if I can't PDF it, it's no good to me.  Do you recommend any certain PDF program to use for output?

**Comment by stolksdorf** [comment]
Use Chrome if you haven't tried that.

**Comment by rob2ee** [comment]
And there we go! Awesome thanX.  Maybe put on the page you HAV to use Chrome to get that PDF save deal.
 Rob Twohy
Twitch: twitch.tv/rob2e
Twitter: @rob2e
Facebook: click here
Rob's DMs Guild Offerings
My Stand-up Comedy Book

|  
|  |  Rob Twohy @rob2e  |  |

  |
| Orange is the New Black Panther #ComicBookTVShows @midnight |
|  
| May 26, 2016 |  |  |  |

  |

**Comment by stolksdorf** [comment]
What were you using before?

**Comment by rob2ee** [comment]
Firefox, and when you print from Firefox, it goes directly to your printers and makes you choose from either printers you have installed, or PDF programs.  Doesn't work right.  Chrome was smooth.
GREAT WORK!  Once you gave me that tip. It works smooth as cake.  Is cake smooth?
 Rob Twohy
Twitch: twitch.tv/rob2e
Twitter: @rob2e
Facebook: click here
Rob's DMs Guild Offerings
My Stand-up Comedy Book

|  
|  |  Rob Twohy @rob2e  |  |

  |
| Orange is the New Black Panther #ComicBookTVShows @midnight |
|  
| May 26, 2016 |  |  |  |

  |

**Comment by stolksdorf** [comment]
Yeah I've been always targetting Chrome mainly. In v2 I spent a lot of time getting the rendering better for firebox and it's much better now, but can't really do anything about the browser's ability to print to PDF. I'll try to make the instructions a bit more clear

**Comment by rob2ee** [comment]
I'm really getting into this. Is there a function I'm missing in markup that will put the vertical barbell bars on the sides of text (DM read aloud) rather than the green box with the folding black (for info)?
 Rob Twohy
Twitch: twitch.tv/rob2e
Twitter: @rob2e
Facebook: click here
Rob's DMs Guild Offerings
My Stand-up Comedy Book

|  
|  |  Rob Twohy @rob2e  |  |

  |
| Orange is the New Black Panther #ComicBookTVShows @midnight |
|  
| May 26, 2016 |  |  |  |

  |

**Comment by stolksdorf** [comment]
The issue has been reported here at #63 . The fix I've been playing around with is adding the ability to switch to completely different styles, like PHB or DMG style. But it's _a lot_ of work. Like at least a dozen hours, and I really don't have the interest in doing it.
