### ISSUE TITLE
Home brewery will not create a new brew

### ISSUE THREAD

**Issue by Tazykat** [stolksdorf/naturalcrit#112]
**Browser Type/Version**: [Google Ultron v90.01]

**Operating System**: [GLaDOS v34.5.8]

**Issue Description**: [The thing won't thing]

**Markdown code to reproduce**:

```
# thing
> thing 2
```

**Related Images** :

**Comment by stolksdorf** [comment]
It does create a new brew. If you continue having this issue please provide more details. If you don't properly fill out the issue, I can't help you.
