### ISSUE TITLE
Monster stat blocks don't properly terminate.

### ISSUE THREAD

**Issue by CaptDeathCap** [stolksdorf/naturalcrit#113]
**Browser Type/Version**: [Chrome]

**Operating System**: [W10]

**Issue Description**: [When attempting to input a Note after a Monster Stat Block, the Note is integrated in the Stat Block, and not creating the note as intended.]

**Markdown code to reproduce**: ___
> ## Ineffable Chihuahua
>*Gargantuan beast, unoriginal neutral*
> ___
> - **Armor Class** 17
> - **Hit Points** 42(1d4 + 5)
> - **Speed** 48ft.
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|1 (-4)|8 (-1)|15 (+3)|18 (+4)|2 (-4)|9 (+0)|
>___
> - **Condition Immunities** swagged
> - **Senses** passive Perception 13
> - **Languages** Common
> - **Challenge** 3 (6135 XP)
> ___
> ***Pack Tactics.*** These guys work together. Like super well, you don't even know.
> ### Actions
> ***Jumping Driver.*** *Melee Weapon Attack:* +4 to hit, reach 5ft., one target. *Hit* 5 (1d6 + 2) 
>
> ***Somersault Stump Fists.*** *Melee Weapon Attack:* +4 to hit, reach 5ft., one target. *Hit* 5 (1d6 + 2) 
>
>
> ##### Time to Drop Knowledge
> Use notes to point out some interesting information. 
> 
> **Tables and lists** both work within a note.

**Comment by stolksdorf** [comment]
Since both use similar syntax, the markdown parser doesn't know when one block ends and the other begins. You need to separate them by basically anything else. A vertical spacing snippet works nicely.

```
___
> ## Ineffable Chihuahua
>*Gargantuan beast, unoriginal neutral*
> ___
> - **Armor Class** 17
> - **Hit Points** 42(1d4 + 5)
> - **Speed** 48ft.
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|1 (-4)|8 (-1)|15 (+3)|18 (+4)|2 (-4)|9 (+0)|
>___
> - **Condition Immunities** swagged
> - **Senses** passive Perception 13
> - **Languages** Common
> - **Challenge** 3 (6135 XP)
> ___
> ***Pack Tactics.*** These guys work together. Like super well, you don't even know.
> ### Actions
> ***Jumping Driver.*** *Melee Weapon Attack:* +4 to hit, reach 5ft., one target. *Hit* 5 (1d6 + 2) 
>
> ***Somersault Stump Fists.*** *Melee Weapon Attack:* +4 to hit, reach 5ft., one target. *Hit* 5 (1d6 + 2) 
>

<div style='margin-top:1px'></div>

> ##### Time to Drop Knowledge
> Use notes to point out some interesting information. 
> 
> **Tables and lists** both work within a note.
```
