### ISSUE TITLE
Adblock blocks shared pages

### ISSUE THREAD

**Issue by YokoAhava** [stolksdorf/naturalcrit#12]
Somewhere in your informational sheet you may want to include that adblock will a shared page if you are trying to view it.

**Comment by stolksdorf** [comment]
Do you have any idea why Adblock is blocking the page?

**Comment by YokoAhava** [comment]
It might be because it senses html injected into the web page. But I am not an expert and just repeating what has been an issue before. 

Also, I use adblock plus, my friend with regular Adblock hasn't had an issue. 
Sorry I'm not the biggest help.

**Comment by stolksdorf** [comment]
Installed Adblock plus on both Chrome and Firefox and both let the share page load fine. Do you mind taking a screenshot of it blocking it, and if Adblock Plus gives you any warnings or details, cap those as well? Thanks!

The only thing I can think of that it wouldn't like is Google Analytics, which I have on the site to track traffic for me. But it should disable it, not block the page completely.

**Comment by YokoAhava** [comment]
I can later, for sure. I'm in class at the moment though. 

But to describe it: it comes up with no message or anything, just a white screen.

**Comment by BobPrime38** [comment]
I was having the same problem with uBlock Origin. uBlock has a logging function to see what's been block and why. The share page was simply hidden by a cosmetic filter that blocks the SharePage class. Disabling this filter displays the page.

**Comment by stolksdorf** [comment]
#88 Follow here
