### ISSUE TITLE
Class table's title comes out weird

### ISSUE THREAD

**Issue by bakgaard** [stolksdorf/naturalcrit#121]
**Browser Type/Version**: Chrome  51.0.2704.63 beta-m (64-bit)

**Operating System**: Windows 10

**Issue Description**: Class table's title comes out weird

**Brew code to reproduce**:

```
#### A title

Some text


##### The Fancyman
___
| Level | Proficiency Bonus | Features | Cantrips Known | Spells Known | 1st | 2nd | 3rd | 4th | 5th | 6th | 7th | 8th | 9th |
|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| 1st | +2 | Orbital Gravedigger | 3 | 1 | 2 | — | — | — | — | — | — | — | — |
| 2nd | +2 | Gunpowder Torturer | 3 | 2 | 2 | — | — | — | — | — | — | — | — |
| 3rd | +2 | Immunological Incantations | 3 | 3 | 3 | — | — | — | — | — | — | — | — |
| 4th | +2 | Ability Score Improvement, Pharmaceutical Gunslinger | 4 | 3 | 3 | — | — | — | — | — | — | — | — |
| 5th | +3 | Spell Analyst | 4 | 4 | 4 | — | — | — | — | — | — | — | — |
| 6th | +3 | Ability Score Improvement, Nuclear Illusionism | 5 | 5 | 4 | — | — | — | — | — | — | — | — |

```

**Related Images** : ![](http://i.imgur.com/HolmfcG.png)

**Comment by stolksdorf** [comment]
Full class tables are meant to be used at the top of a page. They use negative margins to merge the separate title to look as though it's part of the table. Putting anything above it will be pulled in by the negative margin.

Even putting a vertical spacing in between them gets weird, since the table is now technically part of a different flow (since it's mutlicolumn), so the table title gets pushed into the second.

It's all a hot damn mess, and I wish I could go back in time and choose different methods of making things span multicolumn.

**Comment by bakgaard** [comment]
So, I am absolutely no expect in... I don't know what this is..., but looking at the client's ``phb.style.less`` you have a method in the beginning:
```
.useColumns(@multiplier : 1){
	column-count         : 2;
	column-fill          : auto;
	column-gap           : 1cm;
	column-width         : 8cm * @multiplier;
	-webkit-column-count : 2;
	-moz-column-count    : 2;
	-webkit-column-width : 8cm * @multiplier;
	-moz-column-width    : 8cm * @multiplier;
	-webkit-column-gap   : 1cm;
	-moz-column-gap      : 1cm;
}
.phb{
	.useColumns();
	...
```

Any chance you can give ``.useColumns()`` a parameter to specify one or two columns. Or even better, create two different methods, so ``column-gap`` can be set to 0?

With this, starting a 'wide-table', would allow you to call this method in the beginning and in the end?

Of cause, I am being a bit narrow minded. What about people who would like landscape sheets? That must be for another time.

**Comment by stolksdorf** [comment]
If you're looking to make something multicolmn, I just added the wideblock snippet.
