### ISSUE TITLE
H1's overflow their column

### ISSUE THREAD

**Issue by BornToDoStuff** [stolksdorf/NaturalCrit#15]
As shown here. This pushes the text in the next column down and makes a weird space there.
![screen shot 2016-01-13 at 12 34 50](https://cloud.githubusercontent.com/assets/4149032/12302250/4b631c38-b9f2-11e5-8bc7-5c06bd8201d2.png)

H2's are fine though
![screen shot 2016-01-13 at 12 34 20](https://cloud.githubusercontent.com/assets/4149032/12302258/575d23e4-b9f2-11e5-841f-0a53ca34173b.png)

**Comment by stolksdorf** [comment]
That's intentional. Matches the style from the PHB.
