### ISSUE TITLE
Bold text letter spacing

### ISSUE THREAD

**Issue by nickpunt** [stolksdorf/NaturalCrit#16]
Letter spacing is too narrow in bold paragraph font (BookInsanityBold), the letters nearly intersect with one another and looks off compared to normal weight. Suggest adjusting as follows:
letter-spacing: 0.03em;

On the other hand, spacing of bold text *in notes* is too wide (due to ScalaSans font). Suggest adjusting as follows: 
letter-spacing: -0.02em;

**Comment by stolksdorf** [comment]
Wow, this looks much better. Thanks for pointing this point! I'll roll this out with the next deploy :)

**Comment by stolksdorf** [comment]
Added in v1.3. Thanks for the suggestion!
