### ISSUE TITLE
Text flow bug in Safari

### ISSUE THREAD

**Issue by nickpunt** [stolksdorf/NaturalCrit#17]
Text will not flow back to original state when removing then re-adding the following column-end syntax (3x backticks on two lines):

\`\`\`
\`\`\`

Steps to reproduce:
1. Remove above syntax from example text
2. Note will move from left to right column, with empty space above right column
3. Undo removal (add above back to original location)
4. Note will remain in right column, and right column text will fall off to next page.

This will fail in Safari / El Cap, however it works in Chrome / El Cap

**Comment by stolksdorf** [comment]
Thanks for the thorough report. Unfortunately I don't have any intentions of supporting other browsers beyond Chrome.

I have enough cross-browser bugs at my job :P
