### ISSUE TITLE
Make bold text bolder

### ISSUE THREAD

**Issue by touney** [stolksdorf/naturalcrit#18]
Right now it's really hard to distinguish bold text from regular. Definitely not a major issue, just pointing it out.

**Comment by stolksdorf** [comment]
![image](https://cloud.githubusercontent.com/assets/387742/12501789/47e2af44-c08f-11e5-90bb-b4c8a8437ce3.png)

This is what it looks like for me. Is it different for you?

**Comment by touney** [comment]
Sorry for incomplete description. I only meant the bold in the font that is used in the monster stat blocks. For example, the "Armor Class" is bold, the "11" is not, and the difference is really small. Same thing in the other lines.

The bold in the "Actions" section is a bit better (***Short Sword.*** Melee), but if you look at the MM you see it's a lot more bold and thus more clear.

<img width="355" alt="screen shot 2016-01-27 at 14 49 48" src="https://cloud.githubusercontent.com/assets/6035121/12613894/41b72774-c505-11e5-8044-1c5de10b5dc5.png">

Additionally, in the picture you can see that the brown bars at the top and bottom of the stat block are cut off in their left side. This doesn't happen with every stat block, but most of them (maybe depends on what other elements there next to it?). It's only happens on the outer edge (the edge closer to the edge of the 'paper').
