### ISSUE TITLE
Printing view on Chrome reverts to single column.

### ISSUE THREAD

**Issue by Qaeta** [stolksdorf/NaturalCrit#23]
![screenshot 2016-01-14 22 01 15](https://cloud.githubusercontent.com/assets/16673055/12343472/4305c0cc-bb0a-11e5-86dd-c97e795049ae.png)

As seen in the screenshot, when attempting to print from Chrome, it seems to be losing the two column layout.

**Comment by Qaeta** [comment]
This is on Google Chrome Version 47.0.2526.111 m (64-bit)

I will note that the printing seems to work perfectly on Chrome Canary.

**Comment by stolksdorf** [comment]
That is due to this [bug](https://code.google.com/p/chromium/issues/detail?id=99358). I've been waiting for it to get into Chrome Canary. Until it gets rolled into Chrome, I'm just going to write instructions on how to use/install Chrome Canary.

Thanks for the detailed report!
