### ISSUE TITLE
Looks amazing in Chrome Canary

### ISSUE THREAD

**Issue by RCanine** [stolksdorf/NaturalCrit#24]
Hey, just wanted to leave a quick note and thank you for this. After seeing your note on PDF export I tried it in [Chrome Canary](https://www.google.com/chrome/browser/canary.html) and with margins turned off and background images turned on, it looks amazing.

**Comment by stolksdorf** [comment]
Thanks for the update! I was waiting for Chrome Canary to pick up the bug fix. I'm working on making it work well on Firefox right now and then I'll update the project with instructions for both Firefox and Chrome Canary.
