### ISSUE TITLE
Keyboard shortcuts for styling text

### ISSUE THREAD

**Issue by ianfhunter** [stolksdorf/NaturalCrit#37]
I gave this a go myself, but unfortunately I am not familiar with Reactjs, just boring ol' vanilla Javascript :'(

It would be nice if Ctrl+B emboldened items and Ctrl+I italicized them for the Homebrewery - much like you can do with other web based markdown editors. Other combinations could work such as header #'s and Ctrl+Number
(Surprisingly, I can't do this in the GitHub issue editor, one example would be StackOverflow though.)

I will continue to investigate this, but I'm getting to a dead end and it'd be nice if someone could step in and put me out of my misery.

**Comment by stolksdorf** [comment]
I really like the idea, but I'm worried about the slippery slope of features.  I'll experiment adding bold and italics, but realistically it's just saving one or two keystrokes.

**Comment by stolksdorf** [comment]
After experiemnting, I did not find it that useful and could be confusing and difficult to make it behave the way users expect (having text highlighting for example).
