### ISSUE TITLE
Option to report a documetn?

### ISSUE THREAD

**Issue by GypsyRoverNomad** [stolksdorf/NaturalCrit#38]
Can there be an option to request a document for deletion?  In the case of the edit url being lost (my situation), or if there is content that is questionable (copyright infringement)?

**Comment by stolksdorf** [comment]
I have no interest in policing the content of the project and I don't feel like it's my place to. 

However the delete button is a great idea and should have been there from the start. Overlooked that. It'll be added in the next release.

**Comment by GypsyRoverNomad** [comment]
Totally agree that policing would be way above and beyond the scope of such a project!  thank you for taking a look at the delete option!

**Comment by stolksdorf** [comment]
Just added the delete button in v1.3. Thanks again for the suggestion!

**Comment by GypsyRoverNomad** [comment]
You're awesome and thank you so much for giving so much of your time and
skill to the community!
