### ISSUE TITLE
Wont save

### ISSUE THREAD

**Issue by HEATSEEKER911** [stolksdorf/naturalcrit#39]
I started a project and I wrote up to 22 pages and it saved fine. Now for some reason it won't save anything additional I add to it.

**Comment by stolksdorf** [comment]
What's your share link and browser stats?

**Comment by HEATSEEKER911** [comment]
http://www.naturalcrit.com/homebrew/share/4kL6FdfFx I'm using firefox primarily, switched to chrome to see if it had the same problem and it does.

**Comment by stolksdorf** [comment]
I'll take a deeper look later, but a few people have reported some issues when getting to many pages (50+). I suggest just splitting it up for now, or just saving your markdown into notepad on your computer before you leave the tab, just to be safe.

**Comment by nickisnoble** [comment]
I'm having a similar issue – all of a sudden I can't make edits and the preview doesn't update. It's only 6 pages.

http://www.naturalcrit.com/homebrew/share/V1BzR4q0l

Also, while I'm here... thank you for making something so epic.

**Comment by stolksdorf** [comment]
Phew! Fixed in 1.4! The site will only ever render 3 pages at most now. This should fix your issues with long brews, or ones with a ton of issues. Print view still works as expected, so that still might chug your browser (maybe crash it if you wrote a whole text book). Thanks guys!
