### ISSUE TITLE
Chrome Canary

### ISSUE THREAD

**Issue by grimm1989** [stolksdorf/NaturalCrit#41]
i see that it fixed the column issues however the class table seems to have issues. Do you have any ideas how to fix this by any chance?
![capture](https://cloud.githubusercontent.com/assets/17019218/12740905/eae8423a-c945-11e5-9e93-b00ec54cd8df.PNG)

**Comment by stolksdorf** [comment]
When you define class tables within the second column, they will behave weirdly, since the title will try to follow column rules and the grid will try to span multiple columns. I suggest using class tables only at the start of new pages (they are always used this way in the PHB anyways).
