### ISSUE TITLE
Maybe a way to get a 2 columns PDF ?

### ISSUE THREAD

**Issue by Gulix** [stolksdorf/NaturalCrit#43]
Well, I'm really loving the style you put on homebrew. I've played with it this weekend, but the pdf generation was bothering me.
I also use markdown-themeable-pdf package for atom.io : https://atom.io/packages/markdown-themeable-pdf
It helps me generate pdf files for my gaming translations. And I tried to put your css-style in this package, to see what hapened. Well, it generates a two-columns pdf !
Maybe you can look at it if you want to provide a pdf export function.

**Comment by stolksdorf** [comment]
Cool, good to know! Atom is built on top of [Electron](http://electron.atom.io/) which uses node, Chromium, and various other technologies to simulate desktop apps for js. It looks like Electron is using the version of Chromium that has the CSS column fix in it.

[Chrome Canary](https://www.google.com/chrome/browser/canary.html) also has this fix as well. You can use that for PDF exporting until the fix comes to Chrome.
