### ISSUE TITLE
Why no page break in the div.phb ?

### ISSUE THREAD

**Issue by Jokefury** [stolksdorf/NaturalCrit#44]
Hi !

First of all, very thanks for your work, this tool in fantastic !

My problem/sugestion :
I tried to export in pdf (with an online exporter which respects columns and with chrome canary) and I was surprised to found that there is no break between pages. It causes the pages in the pdf don't match the pages in the html.

I manually fixed it by adding a `style="page-break-before: always; page-break-after: always;"` in each div.phb and it works !

Could you please add this feature in the css class .phb or something else ?

**Comment by stolksdorf** [comment]
Added this in v1.3. Thanks for the suggestion!
