### ISSUE TITLE
Table and Indentations

### ISSUE THREAD

**Issue by LikeAJi6** [stolksdorf/NaturalCrit#46]
Referring to page 66 of the _Player's Handbook_, text immediately following a table should be indented. At the moment, the formatting does not do that automatically, and I do not see any way to format it as such. 

P.S. Very cool work. If I get some spare time I might look around your code as I have not done any work like that before.

**Comment by stolksdorf** [comment]
This is fixed in v1.3. Thanks for the heads up!
