### ISSUE TITLE
H1 does not span columns in chrome anymore?

### ISSUE THREAD

**Issue by guppy42** [stolksdorf/NaturalCrit#48]
Chrome Version 48.0.2564.109 (64-bit) (Ubuntu 14.04)

I went to correct a typo when I noticed half the page was falling off - dev console shows;

http://i.imgur.com/lrnd9Gi.png

The warning associated with each exclamation mark are ( from top to bottom ):

- Unkown property name
- Invalid property value ( "all" works )

In a similar vein;

http://i.imgur.com/VIJlei8.png

Have had overflow: hidden added, which breaks my layout - I can work around it but I wonder if it was intentional or not

TYIA

**Comment by stolksdorf** [comment]
Thanks for the excellent issue report! I might use this as a template for future issues.

Just pushed out an update that should fix this. Looks like I left some experimentation code in. Reopen this issue if you're still having problems.
