### ISSUE TITLE
Sugestion/Improvement: brew account

### ISSUE THREAD

**Issue by miguel-pinto-photobox** [stolksdorf/NaturalCrit#50]
Greetings,

I would like to suggest that you add the concept of accounts. Something simple with Email and Password.

this way each person creating brews can easily access all his brews without having to memorize them of store the edit link somewhere in another document or application.

That feature would be great :)

Many thanks,
- Miguel

**Comment by stolksdorf** [comment]
I've built many webapps and adding an account system will be easily as complicated as the rest of the project and wouldn't provide much benefit, and would add friction to the on-boarding experience. Right now someone can hop in, make their brew and no worry about logging in or managing another password.

To combat the memorization issue, I suggest just making a bookmark folder for your edit links.
