### ISSUE TITLE
PDF printing

### ISSUE THREAD

**Issue by NedTurner613** [stolksdorf/NaturalCrit#53]
Your Homebrewery has thus far been a great resource, but whenever I try to save the print version as a PDF, the PDF being saved has no background or borders for the stat blocks. I haven't included the printer friendly snippet in the document, and I'm using Chrome Canary, so I'm not having problems with the two column feature, just getting there to be images when I save it as a PDF. It doesn't have a problem with Print View, either, just saving it as a Pdf.

**Comment by Gulix** [comment]
Did you check the "Background graphics" checkbox in the print page ?

**Comment by NedTurner613** [comment]
Ah HA! Perfect! Thanks!

**Comment by stolksdorf** [comment]
Thanks Gulix!
