### ISSUE TITLE
Printing - Black Lines

### ISSUE THREAD

**Issue by ommin202** [stolksdorf/naturalcrit#54]
**Browser Type/Version: ** [Google Chrome Version 50.0.2658.0 canary (64-bit)]

**Operating System: ** [Windows 7]

**Issue Description** : [Black lines appear on the right and bottom sides of all "notes" and "monster blocks"]

**Markdown code to reproduce: **

```
The moment the nothic is defeated, a burst of light radiates from Androma, temporarily blinding the players. When their vision returns, the wizard is unconscious on the ground, experiencing a *vision*:


> ##### The Vision
> There are many ways to portray the vision. You could print out images and hand them only to the player having the vision, then have them try to explain to the players what they saw. Or you could describe it yourself to keep things mysterious and open-ended.
> 
>The parts of the vision are as follows:
> * A shrouded enemy
> * Any combination of elves and trees
> * A single Treant, burning
> * A monstrous frog
> * The word "Feywild"
> * Magical floating runes (optional, see Sidenote 1)
```

**Images: **
http://imgur.com/ekdBKx2 - see red lines (added) on side/bottom; black lines nearest them shouldn't be there.

**Additional: **
There are some spelling mistakes in the default Brew, in the updates section:
Delete brew butotn has been added to the edit page - Should be button!
Improvements to stlying to get it closer to PHB stlying - Should be styling!

Is there any way to give you some money for making such a fantastic tool?

**Comment by stolksdorf** [comment]
This was due to a bug in Chrome not converting blur effects (like box shadow) properly when making a PDF. This has been fixed by removing the blur effects when you go to print it. This will be released in v2.
