### ISSUE TITLE
Crediting You

### ISSUE THREAD

**Issue by NedTurner613** [stolksdorf/naturalcrit#55]
How would you prefer to be credited for the use of your homebrew creator?

**Comment by kkragenbrink** [comment]
Or paid/patroned?

**Comment by bristolscale7** [comment]
I used homebrewwery for a long adventure I put on the DMs Guild.  I put an acknowledgement and link in the beginning before the DMs Guild legalese.  However, I would gladly contribute a few $ as gratitude.

**Comment by Tsurumah** [comment]
I'd be willing to drop a little bit on patreon, if for nothing else than server costs.

**Comment by stolksdorf** [comment]
Patreon is a good idea. I've looked into a few small donation platforms, but none of them did exactly what I wanted. I'm going to look into setting up a monthly patreon for something tiny (like 0.50 - $1) just to keep the servers running :) 

Thanks for being awesome guys.

**Comment by Tsurumah** [comment]
Doo eet. For $1 a month, I will gladly do that, since pretty much everything I write now for D&D is in the Homebrewery. I do it for En5ider, anyway, too.

**Comment by stolksdorf** [comment]
@NedTurner613 to answer your original question. It's not a huge concern for me to be accredited, although it is a nice gesture. If you feel inclined to do so, something like "Made with [The Homebrewery](naturalcrit.com/homebrew/)" or "template generated by [stolksdorf](https://github.com/stolksdorf)". I made this for the community, so I'm not going to be a stickler on it.

My only concern is that you don't claim you made this project, or copy the code and claim it as your own. Pretty standard open source stuff :)

**Comment by stolksdorf** [comment]
Finally added a Patreon link in v2! Seriously guys, thanks for all the support.
