### ISSUE TITLE
sup/sub tags non-functional

### ISSUE THREAD

**Issue by crashinworld14** [stolksdorf/NaturalCrit#56]
**Browser Type/Version: ** Chrome (v 48.0.2564.116 m) and Firefox (v36.0.1, v38.0.1, v43.0.1, v44.0.2)

**Operating System: ** Windows 10

**Issue Description** : Superscript and subscript HTML tags don't appear to be functional.

**Markdown code to reproduce: **

No markdown.  Just HTML:
`Suptest<sup>1<sup>
<br />
Subtest<sub>2<sub>`

**Images: **
Rendered in Chrome:
![image](https://cloud.githubusercontent.com/assets/17521733/13377036/1512de22-dd90-11e5-9334-ea4caa0d8c78.png)
HTML:
![image](https://cloud.githubusercontent.com/assets/17521733/13377039/2c4df70c-dd90-11e5-9b2f-b7aecf16e172.png)
CSS to let the sup/sub IDs work:
![image](https://cloud.githubusercontent.com/assets/17521733/13377051/4db46c82-dd90-11e5-921c-5bc66114344b.png)

**Comment by stolksdorf** [comment]
Added support for this in v1.3.1 Thanks!
