### ISSUE TITLE
Images are broken

### ISSUE THREAD

**Issue by Druncho** [stolksdorf/naturalcrit#58]
**Browser Type/Version: ** [Google Ultron v90.01]

**Operating System: ** [Windows 7]

**Issue Description** : [No images when I put in images]

**Markdown code to reproduce: **

```
> Click Insert Image
> See if there is image
> There is no image
```

**Images: (there are non) **

**Comment by stolksdorf** [comment]
Can not reproduce. Please provide the markdown code that is causing an issue.

**Comment by wrdclark** [comment]
This is a troll ticket... See [Know Your Meme: Google Ultron](http://knowyourmeme.com/memes/google-ultron).

**Comment by stolksdorf** [comment]
I'm aware, it's the default in the [Issue template](https://github.com/stolksdorf/NaturalCrit/blob/master/.github/issue_template.md). So might not be a troll, ust a very bad issue description. I'll close this in a few days if they don't provide clarification.

**Comment by wrdclark** [comment]
Ah, my bad.

**Comment by Druncho** [comment]
Oh god im seriously sorry for that mess. I installed chrome canary just a few days ago and I thought Ultron is something like a different name for the browser. My bad for that one. 
I don't know if its going to help at all but here's the link for my homebrew: http://www.naturalcrit.com/homebrew/edit/EkePPWR6qg 
Images where there one day and just dissapeard the next one. Now whenever I click to Insert Image nothing happens. It doesnt matter if I change link for the image or not. 

For example:

<img src='http://i.imgur.com/0TylvrE.png' style='position:absolute;bottom:-10px;right:-60px;'/>

**Comment by wrdclark** [comment]
The very top of your brew had a print-friendly tag, that was hiding all the
images. Removing it has restored the background and the inline images.

**Comment by Druncho** [comment]
Well thats a shame because I swear a few days ago I could have white background and images together. I dont want to waste that much ink when I only need few pictures :/

**Comment by wrdclark** [comment]
You can edit the printer-friendly code and delete the "  .phb img{ display
: none;}" line, that will leave the inline images in place.

**Comment by Druncho** [comment]
Yeah it worked. Sorry for all this mess guys. I feel dumb.

**Comment by bristolscale7** [comment]
Hi.  Brilliant tool.  CSS/HtmL luddite here.  How can I get an image to stretch across both columns?
