### ISSUE TITLE
Nested Lists Not Working

### ISSUE THREAD

**Issue by hephalumph** [stolksdorf/naturalcrit#61]
**Browser Type/Version**: [Google Ultron v90.01]

**Operating System**: [GLaDOS v34.5.8]

**Issue Description**: [The thing won't thing]

**Markdown code to reproduce**:

*  list item one
  * nested list item 1
  * nested list item 2
* list item 2

**Related Images** :

**Comment by SecretShop** [comment]
i would have to agree that i was going to use nested lists but realized that i couldn't find the syntax for it.

**Comment by kkragenbrink** [comment]
it's just a CSS issue

http://www.naturalcrit.com/homebrew/edit/rylhOoaT

Fix here.

I'll submit a pull request to fix this later tonight.

**Comment by kkragenbrink** [comment]
Might be able to close this now.
