### ISSUE TITLE
Title page styling

### ISSUE THREAD

**Issue by R0llF0rInitiative** [stolksdorf/NaturalCrit#65]
First off, this thing is awesome. Keep up the amazing work! 

One thing that could be added to make the tool more flexible would be to add the ability to make a title page, or a page without a two-column format and the ability to center certain text. I want to generate a supplement for myself to use while I DM and having a nicely formatted page like this generator creates would be awesome! I might also use it to make spell books for the wizard in the group. 

Thanks!

**Comment by stolksdorf** [comment]
When it comes to more in-depth customization, I suggest learning and using HTML. The Homebrewery is built on top of Markdown which converts into HTML code, and then I let the browser render that. I programmed The Homebrewery to accept HTML to solve your exact issue.

Do some research and experiment with it. Some of the snippets use pure HTML, so you can use those as a template. I'm going to close this issue, but if you have any other questions, feel free to ask it here.
