### ISSUE TITLE
Implement singular page rendering

### ISSUE THREAD

**Issue by SecretShop** [stolksdorf/naturalcrit#68]
**Browser Type/Version**: [Google Chrome  49.0.2623.87 m]

**Operating System**: [Windows 10]

**Issue Description**: [Do you think there is a way to separate pages from each other in the editor? I only ask because large documents might get rather hard to work with and easily find where things are. Maybe create another tab up top with the page number and it brings up the editor on the right JUST with that page markdown. This way it makes it easier to look through! Other than that, wonderful job man, loving this site.]

**Comment by stolksdorf** [comment]
Hmm, that's a very interesting idea. This would also solve the rendering issues several people have been having with larger projects. I'm going to rename this issue to be more specfic and jot down my ideas to solve it when I have some time to implement it.

**Comment by stolksdorf** [comment]
USe react to only render the currently visible page. Implement a faked scrollbar to corresponded with the document length, and it's movement updates which page should be rendered.

Possibly use hash frgaments in the url to track which page should be rendered?

**Comment by nickisnoble** [comment]
I don't think that would be a terrible thing, it would be kind of like viewing a PDF in Preview (on a Mac). You could even allow arrow keys for navigation when focussed on the preview.

Could you also 'chunk' it up, so react would render just a few pages at a time? That might make it better for 'local' scrolling but worse for long scrolling...

**Comment by stolksdorf** [comment]
@nickisnoble you read my mind. Just finished the chunking approach and pushed it out with v1.4! The new version will only ever render at most 3 pages at a time (current, before, and after). Scrolling has been kept the exact same as well, so it's just an improvement all around :). Thanks for the feedback guys!
