### ISSUE TITLE
Suggestion: A site/fourm/page where you can share/post your code or find pre-made codes 

### ISSUE THREAD

**Issue by Ohmyapollo** [stolksdorf/naturalcrit#70]
I personally believe it would be a FANTASTIC idea for there to be a site, be it a reddit subsection, a fourm page on the site, or what not, where people can go and share their stat blocks made on the site.  It would make it so much easier and be much quicker than to sit and create your own every time you wish to use it.  Just a thought.

**Comment by stolksdorf** [comment]
With every submission, anyone can view the source (aka the markdown code used to make it) by hitting the "view source" at the top of the page. Secondly, I suggest using [r/UnearthedArcana](https://www.reddit.com/r/UnearthedArcana/) for sharing and finding submissions. I would say about 10-20% of the posts on that subreddit are already from this site already.

Hopefully that helps.
