### ISSUE TITLE
Display Issues

### ISSUE THREAD

**Issue by Tsurumah** [stolksdorf/NaturalCrit#72]
**Browser Type/Version**: [Google Chrome 49.0.2623.110 m (64-bit)]

**Operating System**: [Windows 7 64 bit]

**Issue Description**: [The Homebrewery does not display correctly for me. My wife's computer displays this the same way, so maybe its something to do with this specific version?]

**Related Images** : http://imgur.com/CjypPcd

**Comment by Tsurumah** [comment]
I thought I'd mention that I've tried changing the encoding in the Dev options for Chrome to various options, including Auto-detect. No dice.

**Comment by stolksdorf** [comment]
Pretty sure this is an OS (maybe chrome) issue and not a site issue. 

Chrome [rolled out a fix for this](https://www.dev-metal.com/fix-ugly-font-rendering-google-chrome/) a while ago.

Try adjusting [Window's graphical settings](http://superuser.com/questions/808874/choppy-font-rendering-on-windows-chrome)

**Comment by Tsurumah** [comment]
Yep, that did it! That's a really weird thing. Ah, well.

**Comment by stolksdorf** [comment]
Great!
