### ISSUE TITLE
Monsters stats block is displayed with wrong style on 2nd column

### ISSUE THREAD

**Issue by miguel-pinto-photobox** [stolksdorf/naturalcrit#73]
The monsters stats block is not displaying the correctly style when displayed on the 2nd column

check this test example: http://www.naturalcrit.com/homebrew/edit/V1lto-COCe

**Comment by Tsurumah** [comment]
Just noticed this myself, actually, since I finally got NaturalCrit to work on my computer just recently.

**Comment by stolksdorf** [comment]
It seems to be a bug with pseudo-elements and CSS-columns. Experiencing the same bug with the shadow on note blocks. I honestly don't know if I can fix this, but I'll take a closer look later.

**Comment by tonymccallie** [comment]
Not a great fix, but this worked for me
```
.phb blockquote {
        box-shadow: 2px 4px 4px #888;
    }
```

Just lessened the shadow a bit

**Comment by Tsurumah** [comment]
I just changed the pixels to 0px and it removed it completely. Works for me!

**Comment by Tsurumah** [comment]
I just wanted to mention that there's no issue with monster stat blocks in the second column when using Google Canary. They display perfectly.

**Comment by stolksdorf** [comment]
Updating this. The solution I want to try is to replace all pseudo-elements that I use for styling with border-images. Border-images look like they render more consistently on chrome and when chrome renders a page to PDF. 

This would affect:
- Monster stat blocks, both borders and internal red lines
- Wing-tipped borders on note blocks

**Comment by stolksdorf** [comment]
In v2 all pseudo-element silliness has been replaced with reliable images. I'll be releasing this shortly after a bit more testing. [Check it out ins taging here](http://natural-crit-staging.herokuapp.com/homebrew/share/rJa2rgBf)
