### ISSUE TITLE
Bleed on the edge for printing.

### ISSUE THREAD

**Issue by tonymccallie** [stolksdorf/naturalcrit#74]
I was trying to have the PDF I made printed (by my friend at a print shop) for my group and my friend was telling me I need to add 1/2 in bleed to my pages so they can cut for full bleed. If I pull down my own version of the repo to edit, where would I find template information to set my pdf up like this? If I can get it set up, I'd be happy to share the changes for anyone who might need it.

**Comment by stolksdorf** [comment]
Actually, if you know the CSS to make it happen, you can input it directly into your brew, just wrap it in `<style>` tags. Each page is a div with the class `.phb`, Once you find the css that works for you, please share it and I'll add it as a snippet on the site :)

Let me know if you have any issues doing this.

**Comment by tonymccallie** [comment]
I was actually able to figure this out, but it's a bit complicated. Here's the css:
```
.phb {
        width: 228.6mm;
        height: 292.1mm;
        padding: 1.635cm 2.335cm;
        padding-bottom: 2.135cm;
    }
    .phb:after {
        width: 95%;
        left: 2.5%;
        bottom: 2%;
    }
    .phb .pageNumber {
        bottom: 3.4%;
        right: 2.8%;
    }
    .phb:nth-child(even) .pageNumber {
        left: 2.7%
    }
    .phb:first-child:after {
        background: none;
    }
    @page {
        size: 9in 11.5in;
    }
    @media print {
        .phb {
            background-color: transparent;
            background-image: none;
        }
    }
```

But getting the PDF's is tricky. Chrome (on a mac anyway) doesn't allow custom page sizes. For me, I had to set the page size to Tabloid/11x17 to get PDF's large enough to hold the bleed. I was also using this on some of my pages to see where the bleed cuts would be, but would remove for production:
```
<img src="http://tonymccallie.com/webroot/arctoris/crop_lines.png" style="position: absolute; top: 0; left: 0; width: 100%;" />
```
Hope this helps someone else out.
