### ISSUE TITLE
Homebrewery 1.4 Problems!

### ISSUE THREAD

**Issue by wesdecker** [stolksdorf/naturalcrit#75]
**Browser Type/Version**: [Chrome Canary]

**Operating System**: [Windows 7]

**Issue Description**: [Only the first two pages of each Homebrew will load!]

```
First, love the site. It's been a huge boon for myself and my players, allowing me to compile and create homebrew for them to easily reference. The patch pushed through today, however, seems to only be loading the first couple pages of each URL. My players and I have tested Homebrewery links from multiple sources and across multiple browsers. It seems like the update intending to partially render pages isn't working as intended.

```

**Comment by mc680x0** [comment]
I'd like to add that I'm seeing this on Chrome stable on Windows 7 x64 and Gentoo Linux also.

**Comment by stolksdorf** [comment]
Yeah, there were a ton of CSS problems sorry. I was too excited to get partial rendering working. I've reverted to v1.3 until I've fixed the issues. I've also setup a proper staging environment to avoid issues like this in the future.
