### ISSUE TITLE
Fancy table style not working on Canary on OSX. Was a few days ago.

### ISSUE THREAD

**Issue by tonymccallie** [stolksdorf/naturalcrit#76]
**Browser Type/Version**: [ Version 51.0.2702.0 canary (64-bit)]

**Operating System**: [OSX El Capitan]

**Issue Description**: [The pretty table borders aren't showing up.]

I've tried refreshing and restarting the browser. When I view it in normal Chrome, it looks fine, but in Canary (where I need to be to print) the borders aren't working.

**Markdown code to reproduce**:
##### The Concierge
___
| Level | Proficiency Bonus | Features | Cantrips Known | Spells Known | 1st | 2nd | 3rd | 4th | 5th | 6th | 7th | 8th | 9th |
|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| 1st | +1 | Pharmaceutical Gunslinger | 3 | 1 | 2 | — | — | — | — | — | — | — | — |
| 2nd | +2 | Gunpowder Torturer | 4 | 1 | 3 | — | — | — | — | — | — | — | — |
| 3rd | +2 | Police Necromancer | 5 | 1 | 3 | — | — | — | — | — | — | — | — |
| 4th | +2 | Plasma Outlaw | 5 | 1 | 3 | — | — | — | — | — | — | — | — |
| 5th | +2 | Statistical Occultism | 5 | 1 | 3 | — | — | — | — | — | — | — | — |
| 6th | +2 | Genetic Banishing | 6 | 1 | 4 | 1 | — | — | — | — | — | — | — |
| 7th | +3 | Ability Score Improvement | 6 | 2 | 4 | 2 | — | — | — | — | — | — | — |
| 8th | +3 | Demonic Anthropology | 7 | 2 | 4 | 2 | — | — | — | — | — | — | — |
| 9th | +3 | Immunological Incantations | 7 | 2 | 4 | 3 | — | — | — | — | — | — | — |
| 10th | +3 | Ability Score Improvement | 7 | 2 | 4 | 3 | — | — | — | — | — | — | — |
| 11th | +3 | Ability Score Improvement | 8 | 3 | 4 | 3 | 1 | — | — | — | — | — | — |

```
# thing
> thing 2
```

**Related Images** :
![screen shot 2016-04-07 at 1 54 37 pm](https://cloud.githubusercontent.com/assets/35459/14363131/4eab4ce4-fcc8-11e5-912e-0d63167f506a.png)

**Comment by stolksdorf** [comment]
I believe this broke with the v1.4 push. I've reverted back to v1.3 and it looks like it's working.

**Comment by tonymccallie** [comment]
Thanks!
