### ISSUE TITLE
Saving to PDF produces different results than what is shown in web browser

### ISSUE THREAD

**Issue by briangun1** [stolksdorf/naturalcrit#78]
**Browser Type/Version**: Chrome Canary and Chrome / Version 49.0.2623.110 (64-bit)

**Operating System**: Mac OSX Yosemite (10.10.5) and Windows 7

**Issue Description**: Text and block drop shadows are different (darker and thicker) when saving as a PDF in Chrome. (See pictures)

**Related Images** : 
Screenshot of website: http://imgur.com/uVBcs51
Screenshot of PDF: http://imgur.com/x9ubzGG

**Comment by stolksdorf** [comment]
Those black boxes will be fixed in v2 (currently in staging and releasing soon)
