### ISSUE TITLE
Configure weekly database backups

### ISSUE THREAD

**Issue by stolksdorf** [stolksdorf/naturalcrit#80]
Can never be too safe

**Comment by tonymccallie** [comment]
Ever look at rsnapshot? I have it running on a separate server so that I have incremental back ups every 4 hours/7 days/4 weeks/6 months (configurable) and it manages storage nicely. I then run a nightly cron to dump sql tables so I have daily backups.

**Comment by stolksdorf** [comment]
I'm using mongoDB with mLab, and they have a built in feature for backups, I just added this as a reminder to configure it. It costs a bit, hence why I didn't do it in the beginning, I never thought this project would get so popular !

**Comment by stolksdorf** [comment]
Done in v2
