### ISSUE TITLE
Print to PDF tutorial incomplete.

### ISSUE THREAD

**Issue by CaptDeathCap** [stolksdorf/naturalcrit#89]
**Browser Type/Version**: [Chrome Canary, as instructed in the template 'homebrew']

**Operating System**: [Windows 10]

**Issue Description**: [Save to PDF on chrome defaults to the box for 'background graphics' not being ticked, completely hiding the pretty background and footnotes. VERY CONFUSING. Please add to the tutorial! =D]

**Markdown code to reproduce**:

```
# thing
> thing 2
```

**Related Images** :

**Comment by stolksdorf** [comment]
Updated in v2
