### ISSUE TITLE
Automatic page numbering

### ISSUE THREAD

**Issue by Defoil** [stolksdorf/naturalcrit#90]
**Suggestion**

It would be awesome if you could insert some form of automatic page numbering.

**Comment by stolksdorf** [comment]
As it works currently, this feature would required automatic code editing, which is something I want to avoid (the snippets being a form of manual code editing). Also, the use case would be too narrow/difficult to configure to meet everyone's needs.

**Comment by Defoil** [comment]
Understandable!
