### ISSUE TITLE
Spell list formating

### ISSUE THREAD

**Issue by mlenser** [stolksdorf/naturalcrit#92]
Please create some formatting that will allow us to format spells in 4 columns as they appear on page 207-211 of the PHB.

Thanks!

**Comment by wrdclark** [comment]
There's a workaround using CSS that targets a specific page number. Just change the number in the 'nth-of-type' brackets to the page you want to affect.

For 3 columns:
```
.phb:nth-of-type(99){
    column-count: 3;
    column-width: 5cm;
    -webkit-column-count: 3;
    -webkit-column-width: 5cm;
}
```

For 4 columns:
```
.phb:nth-of-type(99){
    column-count: 4;
    column-width: 3.5cm;
    -webkit-column-count: 4;
    -webkit-column-width: 3.5cm;
}
```

**Comment by mlenser** [comment]
Awesome! Thanks!

**Comment by wrdclark** [comment]
CSS columns apply to the entirety of an element (a whole page in this case). To affect part of a page, you'd need a wrapper element around the part you want to have different columns. I've not had much luck wrapping entire sections of the document in a div, as it breaks CSS selectors looking for direct descendants.

**Comment by stolksdorf** [comment]
Sorry this took so long to get to. A bit in-depth about why this took so long. Essentially I'm running out of syntax to use in standard Markdown. There are too many unique elements in the PHB-style to be mapped. I solved this earlier by stacking certain elements together (eg. an `<hr>` before a `blockquote` turns it into monster state block), but those are getting unwieldy. I would like to simply wrap these in `div`s with classes, but unfortunately Markdown stops processing when within HTML blocks. 

It took a while, but to get around this I wrote my own override to the Markdown parser and lexer to process Markdown within a simple div class wrapper. Meaning I can now wrap markdown in simple divs to change how the markup renders. 

This should open the door very many more unique elements, but the first one I decided to tackle was the Spell List. I've added a new snippet showing how it works. I've tried my best to replicate the style from the PHB. 

I hope you guys find this useful :)

This update is deployed in v2.1.0

**Comment by mlenser** [comment]
Hi Scott,

The height of the main page is now limited via inline styling. See http://i.imgur.com/wvrugEE.png

Other than that the new system looks nice. Thanks for working on this!

**Comment by stolksdorf** [comment]
I don't think your issue is caused by inline styling. Check out #109. Just refresh your browser for now. I'll try to fix this issue soon.

**Comment by mlenser** [comment]
It is an inline style on .brewRenderer

But a refresh fixes it so not a huge need to fix. I just noticed it now after upgrading to chrome 51.

**Comment by stolksdorf** [comment]
Yup, the inline style is added via javascript when the page loads it does some math on your browser size and other elements to figure out how tall the brewRender should be. I've tried attaching the height code to the window resize event, but it caused other rendering issues that are IMO worse than the current bug. 

It has nothing to do with your chrome version. This change occurred with the update to the UI in v2.0.0

**Comment by mlenser** [comment]
What is the specified height used for? Wouldn't flexbox be able to cover whatever usage you need it for?

**Comment by stolksdorf** [comment]
It has to do with interactions with several layers on flexboxes, and a bunch of 100% heights. You can check out the code. If you have any suggestions on fixing it, please submit a PR.

**Comment by mlenser** [comment]
Ah. I maaay take a look if I get bored some day, but in general have too many side projects with the 5e shaped sheet for roll20 and the PF -> 5e converter.

I sent you some patreon monies either way. If you don't hear back on this keep up the good work. :)

**Comment by stolksdorf** [comment]
You're a champ, Thanks man! Hopefully I'll get to this, or come up with a better solution later. But for now I want to spend my time working on the new tools :tada:
