### ISSUE TITLE
Monster stat blocks don't appear correct on the right column.

### ISSUE THREAD

**Issue by McToomin** [stolksdorf/naturalcrit#93]
**Browser Type/Version**: Google Chrome version 50.0.2661.94 m

**Operating System**: Windows 7

**Issue Description**: Monster stat blocks don't appear correctly when they're in the right column.

**Markdown code to reproduce**: As far as I can tell, it happens to any monster stat block that appears in the right column, whether it's there because it doesn't fit on the first column, or if you purposefully put it there by doing a column break.

**Related Images** : 
![monsterstats](https://cloud.githubusercontent.com/assets/17690795/15218127/78232a9a-182c-11e6-87fe-6c205aff0bed.png)

**Comment by stolksdorf** [comment]
I've been working on a complete overhaul of the site. [Current version is up on staging](http://natural-crit-staging.herokuapp.com/homebrew/share/rJa2rgBf). Looks like the problem is fixed, but let me know if anything is froggy.
