### ISSUE TITLE
V2 broke print to pdf

### ISSUE THREAD

**Issue by CaptDeathCap** [stolksdorf/naturalcrit#97]
**Browser Type/Version**: [Any version of Chrome]

**Operating System**: [W10]

**Issue Description**: [V2.0.0 broke the Print to Pdf feature. Pages are not displaying properly in print mode. Tried on multiple systems and chrome browsers. Printing still works on cached legacy versions of the homebrewery.]

**Markdown code to reproduce**:

```
# thing
> thing 2
```

**Related Images** :

**Comment by stolksdorf** [comment]
I was just able to print 12 randomly selected brews from the database to PDF perfectly fine. Running Chrome on Windows. You're going to have to be more specific on how replicate and what exactly the issue is.
