### ISSUE TITLE
Share Link...

### ISSUE THREAD

**Issue by dracoknight425** [stolksdorf/naturalcrit#99]
The "share link" has been removed. This is particularly frustrating as I'm working on a source book with a number of friends.

**Comment by stolksdorf** [comment]
I don't know why you'd think I would remove one of the core features of my tool intentionally, without mentioning it in some way.

Re-open this issue with an explanation of where you expected it to be/function like, or the url that you are experiencing this on, or a screenshot, _anything_ to help you solve this.
